### PR TITLE
test: add TestRunAutoQuotaId and TestRunQuotaId cases

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

### Ⅰ. Describe what this PR did
add TestRunAutoQuotaId and TestRunQuotaId cases

### Ⅱ. Does this pull request fix one issue?
NA

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
NA

### Ⅳ. Describe how to verify it
NA

### Ⅴ. Special notes for reviews
NA

### CODE REVIEW

**Comment by sunyuan3** [comment]
The travis CI failure is caused by this pr. The two cases are skipped.

**Comment by sunyuan3** [comment]
ping @rudyfly

**Comment by chuanchang** [comment]
@sunyuan3 IMO, it had better to define a variable for QuotaId and AutoQuotaId, what do you think?

**Comment by sunyuan3** [comment]
> @sunyuan3 IMO, it had better to define a variable for QuotaId and AutoQuotaId, what do you think?

Nice Catch. I will update the pr according to your suggestion.

**Pull request closed without merging**
