### PR TITLE
[WIP] Upgrade to containerd v1.2

### PR DESCRIPTION
**Pull request by fuweid**
### Ⅰ. Describe what this PR did

The containerd has been improved a lot in v1.2, which makes the service
stable than before. Based on this, we need to do the upgrade.

```
using following commands to update the vendor

govendor fetch github.com/containerd/containerd/...@v1.2.0
govendor fetch github.com/gogo/protobuf/...@v1.0.0
govendor fetch github.com/gogo/googleapis/...@08a7655d27152912db7aaf4f983275eaf8d128ef
govendor fetch google.golang.org/grpc/...@v1.12.0
govendor fetch github.com/golang/protobuf/...@v1.1.0
```

Basically, both the contaienrd and shim API interfaces are stable so
that we don't need to worry about the remote API calls. However, the
package level interface has been changed a lot. The commit is used to
align with containerd@v1.2.0.

    1. events part:
       using exchange event helper instead of raw grpc conn

    2. image part:
      a. import:
         new Import interface makes the import easier without Importer.

      b. commit:
         content helper has been upgraded with less arguments for caller.
         and `diff` package separates the Applier and Comparer interfaces.
         The changes can make the code clear in PouchContainer

    3. lease:
      containerd client doesn't provide ListLeases interface directly.
      PouchContainer needs to get LeasesService and make the call by itself.

    4. container IO:
      remove codes which comes from containerd. The code was used to align
      with containerd v1.2, which can make upgrade work easier. For now, we
      can remove this.

I also use subshell to run the `integration::ping_pouchd` command so that the error log can show up in CI.

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

no need

### Ⅳ. Describe how to verify it

use existing CI testing case

### Ⅴ. Special notes for reviews

I separate the change into two commits because the vendor change is too big. 
There are somethings need to do after this PR, for example, it is time to remove the ctrd/wrapper_client.go because the grpc has been updated and it can support the [defaultMaxStreamsClient](https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/defaults.go#L34)

related to https://github.com/containerd/containerd/issues/2862

### CODE REVIEW

**Comment by fuweid** [comment]
the first commit is for vendor update and the second one is for code change. hope it can help.

**Comment by fuweid** [comment]
still investigate the failed cases about load/save functionality. It seems that the containerd export functionality doesn't support the image which has several manifests.

**Comment by Ace-Tang** [comment]
Hold this pr

**Comment by fuweid** [comment]
close it and re-create other one

**Pull request closed without merging**
