### PR TITLE
test: add unit test for cri

### PR DESCRIPTION
**Pull request by ZouRui89**
Signed-off-by: Zou Rui <21751189@zju.edu.cn>

### Ⅰ. Describe what this PR did
add unit test for cri

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by ZouRui89** [comment]
I will add more unit test for cri these days. Please do not merge this now.

**Comment by ZouRui89** [comment]
You may need to review this pr, since I have deleted the whole cri_test.go file.
Every function in that file is corresponding to cri_utils.go. 
So, I remove those functions to cri_utils_test.go. @allencloud

**Comment by ZouRui89** [comment]
There are still some unit tests missing in cri_utils_test.go, since those functions in cri_utils.go are unfinished. Maybe we can merge this pr now and more work will be done in the future.

**Comment by Letty5411** [comment]
LGTM

**Comment by allencloud** [comment]
Thanks for your work. @ZouRui89

**Pull request merged**
