### PR TITLE
bugfix: should use `go get -u golang.org/x/lint/golint`

### PR DESCRIPTION
**Pull request by fuweid**
Signed-off-by: Wei Fu <fhfuwei@163.com>

### Ⅰ. Describe what this PR did

Fix the golint download issue and make the ci happy.

### CODE REVIEW

**Comment by oiooj** [comment]
@fuweid  It seems that `golang.org/x/lint` already removed. 

It's looks not good to me.

**Comment by oiooj** [comment]
You're right, but the `golang.org/x/lint` not exist. Maybe something wrong there. I think we should not use this reop at this point.

**Comment by allencloud** [comment]
Thanks for your work @fuweid and your feedback @oiooj 
LGTM

**Comment by oiooj** [comment]
@fuweid The `golang.org/x/lint` 404 issue is solved. 

Are you OK to pull a new request to change this ?

**Comment by fuweid** [comment]
hi @oiooj , the PR is coming #1201 please hold on a sec.

**Pull request merged**
