### PR TITLE
feature: populate empty volumes when creating container

### PR DESCRIPTION
**Pull request by shaloulcy**
Signed-off-by: Eric Li <lcy041536@gmail.com>

### Ⅰ. Describe what this PR did

if the volume is empty and image path is not empty, we will populate the volume with the image data

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by allencloud** [comment]
I think this could definitely add an integration test. WDYT? @shaloulcy @YaoZengzeng

**Comment by shaloulcy** [comment]
@YaoZengzeng  Are you interested to add an integration test? thanks~

**Comment by YaoZengzeng** [comment]
@shaloulcy After this PR being merged, I'll write a test for it.

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
