### PR TITLE
bugfix: setup hook in advance to avoid panic if no prestart hook setup before

### PR DESCRIPTION
**Pull request by yyb196**
Signed-off-by: Frank Yang <yyb196@gmail.com>

### Ⅰ. Describe what this PR did
setup hook in advance to avoid panic if no prestart hook setup before this place

### CODE REVIEW

**Comment by allencloud** [comment]
Could we add an integration test to cover this? @yyb196 @wangforthinker

**Comment by allencloud** [comment]
I changed the title. What do you think of this pull request?
I wish that you could help to review this, since this is a P0. @rudyfly

**Comment by HusterWan** [comment]
LGTM

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
