### PR TITLE
bugfix: fix log-opt parse fail if value contains comma

### LINKED ISSUE #1715: [bug] pouch cli and daemon cannot parse log-opt if the value contains comma
### Ⅰ. Issue Description

I want to pass the default `log-opt` to daemon, but it fails.

```
➜  pouch git:(master) pouchd --log-opt "env=APP,VERSION"
Error: the format must be key=value
ERRO[0000] the format must be key=value
```

It also fails in cli if the value contains comma.

```
➜  pouch git:(master) pouch run -it --log-opt env=VERSION,APP busybox echo hello
Error: failed to run container: the format must be key=value
```

### Ⅱ. Describe what happened

According to https://godoc.org/github.com/spf13/pflag#StringSlice, it will parse `a,b` into two options.

### Ⅲ. Describe what you expected to happen

It should parse successfully.

> NOTE: use https://godoc.org/github.com/spf13/pflag#StringArrayP

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

```
➜  pouch git:(master) pouch version
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-07-11T18:10:34+08:00
GitCommit:       0.4.0-577-gd76b476
GoVersion:       go1.9.1
KernelVersion:   4.4.0-130-generic
Os:              linux
Version:         0.5.0
```

### PR DESCRIPTION
**Pull request by Frankzhaopku**
### Ⅰ. Describe what this PR did
Fix log-opt parse fail if value contains comma.

The [`StringSliceVar`](https://godoc.org/github.com/spf13/pflag#StringSliceVar) is like `StringSlice`, it will split the value with comma and assign to a pointer of string array. So the parse result of `--log-opt env=APP,VERSION` would be `[]string{"env=APP", "VERSION"}`, this array will be passed into [`ConvertKVStringToMap`](https://github.com/alibaba/pouch/blob/master/pkg/utils/utils.go#L424) func which demand the value with format of `"key=value"`, so "VERSION" will cause a parse err.

But [`StringArrayVar`](https://godoc.org/github.com/spf13/pflag#StringArrayVar) would not try to separate the value with comma and pass the value as a whole string which won't cause the err.

### Ⅱ. Does this pull request fix one issue?

fixes #1715

### CODE REVIEW

**Comment by allencloud** [comment]
Could you add more details about why the `StringSliceVar ` is incorrect? @Frankzhaopku

**Comment by Frankzhaopku** [comment]
@allencloud The [`StringSliceVar`](https://godoc.org/github.com/spf13/pflag#StringSliceVar) is like `StringSlice`, it will split the value with comma and assign to a pointer of string array. So the parse result of `--log-opt env=APP,VERSION` would be `[]string{"env=APP", "VERSION"}`, this array will be passed into [`ConvertKVStringToMap`](https://github.com/alibaba/pouch/blob/master/pkg/utils/utils.go#L424) func which demand the value with format of `"key=value"`, so "VERSION" will cause a parse err.
But [`StringArrayVar`](https://godoc.org/github.com/spf13/pflag#StringArrayVar) would not try to separate the value with comma and pass the value as a whole string which won't cause the err.

**Comment by Ace-Tang** [comment]
Hi @Frankzhaopku , Could you add your explain into commit, so other can know from commit, thanks

**Comment by Frankzhaopku** [comment]
Need to remake the PR.

**Comment by Ace-Tang** [comment]
@Frankzhaopku , you can force push your branch and no need to open a new pr, just a advise.

**Pull request closed without merging**
