### PR TITLE
feature: make env support inputting empty value when creation

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

### Ⅰ. Describe what this PR did

env management of container may have some incompatibilities there. Here is the case:

For create env:
1. --env a=b: add env a with value b in container 
2. --env a=: add env a with empty value in container
3. --env a: remove env a in container's envs which are inherited from image;
4. --env a="b c": add env a with value "b c" in container, which has a whitespace there.

What I did:
1. modify the cli instruction;
2. modify the swagger.yml to be more clear;
3. add test case

### Ⅱ. Does this pull request fix one issue?

none

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
added

### Ⅳ. Describe how to verify it
none

### Ⅴ. Special notes for reviews

@wangforthinker @zjumoon01 @rudyfly

### CODE REVIEW

**Comment by allencloud** [comment]
I think this PR is going to fail, I am just testing to see whether the current implementation meets the demand.

**Comment by wangforthinker** [comment]
LGTM

**Comment by zjumoon01** [comment]
Caution function updateContainerEnv() which writes env to /etc/profile.d/pouchenv.sh in container.
It splits env by "=", and use "parts[1]" without checking split result's length.  I'm not sure whether that can cause panic if len(parts)=1 .

**Comment by allencloud** [comment]
@zjumoon01 

image

**Comment by zjumoon01** [comment]
> @zjumoon01
> 
> image

all right

**Comment by allencloud** [comment]
Thanks for your review. @wangforthinker @zjumoon01 
Merging...

**Pull request merged**
