### PR TITLE
test: add lxcfs binary check

### LINKED ISSUE #606: [bug] lxcfs related tests should check the lxcfs binary
**Issue Description**
Lxcfs related tests should check the following conditions before running:
1. `/usr/bin/lxcfs` exists
2. `pouchd` start with option `--enable-lxcfs=true --lxcfs=/usr/bin/lxcfs`

**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty <letty.ll@alibaba-inc.com>

### Ⅰ. Describe what this PR did
fix #606

### CODE REVIEW

**Comment by Ace-Tang** [comment]
Could you also add `--enable-lxcfs` flag in pouchd flag check, @Letty5411

**Comment by allencloud** [comment]
LGTM

**Comment by Letty5411** [comment]
@Ace-Tang  add it, PTAL.

**Comment by Ace-Tang** [comment]
Good, fix it will fail in my ubuntu.

**Pull request merged**
