### PR TITLE
refactor: upgrade reference pkg

### PR DESCRIPTION
**Pull request by 0x04C2**
Signed-off-by: Wei Fu <fhfuwei@163.com>

**1.Describe what this PR did**

Upgrade reference pkg.

**2.Does this pull request fix one issue?** 

NONE

**3.Describe how you did it**

Use interface to describe the behaviour about `Named`, `Tagged` and `Digested` reference. 

The behaviour comes from user input. For example, user maybe inputs

| inputs        | behaviour           | 
| ------------- |:-------------:|
| docker.io/library/redis      | Named |
| docker.io/library/redis:3.2      | Tagged      | 
| sha256:7173b809ca12ec5dee4506cd86be934c4596dd234ee82c0662eac04a8c2c71dc | Digested      |

For the `pull` command, the `latest` tag can be ignored and `pouch` will use `WithDefaultTagIfMissing` to add `latest` tag before pull.

For the default registry case, we can use `Domain` function to get domain information from input.

**4.Describe how to verify it**

I don't think we can add `latest` tag in `cli` command except `pull`.

Both the mapping from `image ID` to `image digest` or the mapping from `image name[:tag]` to `image digest` are handled in `daemon`. Why?  Because the context is stored in backend. If we changed the user input, the backend can't get the original information.

For this case, the process about finding image id should be:

```
1. retrieve digest from cache
map[image name:tag]image digest

2. use go-patricia to search the idOrName if step 1 failed
NOTE: if idOrName is pure short ID or digest, the go-patricia maybe find the target.
```

Does it make senses? 

**5.Special notes for reviews**

cc @allencloud and @zeppp

### CODE REVIEW

**Comment by 0x04C2** [comment]
@allencloud  and @zeppp 

I have updated the reference package and support to use image ID in create/run/rmi/inspect command. Please take a look, thanks

**Comment by allencloud** [comment]
Thanks a lot for your work. I will review this ASAP tomorrow. @0x04C2

**Comment by 0x04C2** [comment]
OK. there is No rush :grin:

**Comment by zeppp** [comment]
Totally LGTM. I think we should merge this ASAP to avoid  blocking the CRI implementation.
PTAL @allencloud

**Comment by allencloud** [comment]
LGTM, Thanks @zeppp .
And let us move this much faster. So just kick the ball.

**Pull request merged**
