### PR TITLE
fix: update stop.go to add cli long description and example

### PR DESCRIPTION
**Pull request by ZJLavender**
**1.Describe what this PR did**
add some descriptions and examples
**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
You do not have to open a new PR. You could give take  a look at the CI failure message and update your PR according to the error. 
And feel free to tell us in comment or open a new issue if you need any help.

**Comment by allencloud** [comment]
Thanks for your contribution. @ZJLavender
Maybe you can take a look at https://github.com/alibaba/pouch/blob/master/cli/create.go for an example. 
I think following an example would help a lot.

**Comment by ZJLavender** [comment]
OK,I will have a try

**Comment by allencloud** [comment]
LGTM. Thanks for your contribution. @ZJLavender We are so happy to have you in pouch community. 😄 🦁 🍺

**Pull request merged**
