### PR TITLE
fix: unknown command "ls" for "pouch images"

### PR DESCRIPTION
**Pull request by tiny1990**
**1.Describe what this PR did**
fix doc
**2.Does this pull request fix one issue?** 

NONE
**3.Describe how you did it**
source code build and ./pouch images ls
**4.Describe how to verify it**
NONE

### CODE REVIEW

**Comment by 0x04C2** [comment]
Hi @tiny1990 , the `pouch images` is expected command. This command doesn't need the `ls`.

**Comment by tiny1990** [comment]
@0x04C2 so i delete ls .

**Comment by 0x04C2** [comment]
Sorry, I make a mistake... Good catch!!!!

**Comment by tiny1990** [comment]
@0x04C2  a hello world pull request

**Comment by Letty5411** [comment]
@tiny1990 Could you change your commit message with title "fix: " ?

**Comment by tiny1990** [comment]
@Letty5411  change to refactor?

**Comment by 0x04C2** [comment]
Hi @tiny1990 , please use the following command to update your commit message:

```
git commit -s --amend
```

And `git push -f origin master`

**Comment by tiny1990** [comment]
@0x04C2  thanks

**Comment by Letty5411** [comment]
@tiny1990 change to `fix` is OK.

**Comment by Letty5411** [comment]
LGTM

**Pull request merged**
