### PR TITLE
feature: copy ownship when do copy image content

### PR DESCRIPTION
**Pull request by wangforthinker**
Signed-off-by: allen.wang <allen.wq@alipay.com>

### Ⅰ. Describe what this PR did
when copy image content to volume, also do copy uid and gid from source. 

### Ⅱ. Does this pull request fix one issue?

none.

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
no need.

### CODE REVIEW

**Comment by allencloud** [comment]
CI failed: @wangforthinker 
```
--- FAIL: TestCopyOwnership (0.00s)
	container_storage_test.go:94: failed to chown /tmp/testCopyOwnerShip119167603/sourceDir: chown /tmp/testCopyOwnerShip119167603/sourceDir: operation not permitted
```

**Comment by wangforthinker** [comment]
> CI failed: @wangforthinker
> 
> ```
> --- FAIL: TestCopyOwnership (0.00s)
> 	container_storage_test.go:94: failed to chown /tmp/testCopyOwnerShip119167603/sourceDir: chown /tmp/testCopyOwnerShip119167603/sourceDir: operation not permitted
> ```

chown needs root permission, but go test does not have this  permission. So I cancel this test.

**Comment by rudyfly** [comment]
Can you add test case for it ?

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
