### PR TITLE
feature: implement execSync of cri manager

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

**1.Describe what this PR did**

**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

Maybe the [cri-tools](https://github.com/kubernetes-incubator/cri-tools) is what you need.

We may use the following method to verify that we can execSyn container:
```
[root@pouch-test cri-tools]# cat sandbox-config.json
{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
[root@pouch-test cri-tools]# crictl runs sandbox-config.json
bf1b6fc8cf9ec4c496fe620f1df101266208203bc73f3e01ef2cb7027fd7cec3
[root@pouch-test cri-tools]# cat container-config.json 
{
  "metadata": {
      "name": "busybox"
  },
  "image":{
      "image": "docker.io/library/busybox:latest"
  },
  "command": [
      "top"
  ],
  "linux": {
  }
}
[root@pouch-test cri-tools]# crictl create bf1b6fc8cf9ec4c496fe620f1df101266208203bc73f3e01ef2cb7027fd7cec3 container-config.json sandbox-config.json
6bd4a19122fe56f3972968aa21e5c72b90bfdad1e162c5aa54038959ee49df2a
[root@pouch-test cri-tools]# crictl start 6bd4a19122fe56f3972968aa21e5c72b90bfdad1e162c5aa54038959ee49df2a
[root@pouch-test cri-tools]# crictl exec -s 6bd4a19122fe56f3972968aa21e5c72b90bfdad1e162c5aa54038959ee49df2a echo "hello world"
hello world
```
**5.Special notes for reviews**

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@allencloud PTAL. 

It has already passed the corresponding test in cri-tools.

Since #617 has not been merged, we could not add `basic operations on container` test set into CI 
 temporarily :)

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
I think we still some tiny issues in #617, so maybe we need some time fix this.
Ping @0x04C2, could you help solve the reference package refactoring thing ASAP？
Since CRI implementation thing may be blocked by your work. 

More feature demand, you may refer to @zeppp . We can communicate with each other any time.

**Comment by 0x04C2** [comment]
OK. I will do this in two days @allencloud

**Comment by allencloud** [comment]
Thanks @0x04C2 
And I am merging this now.

**Pull request merged**
