### PR TITLE
enhance: add volume lock

### PR DESCRIPTION
**Pull request by shaloulcy**
Signed-off-by: Eric Li <lcy041536@gmail.com>

### Ⅰ. Describe what this PR did

Right now,  the volume core has no lock. It may have problems in some race conditions. In this pull request, we add volume lock.

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by fuweid** [comment]
@shaloulcy Could you mind to provide more information about impact if we have the race condition?

**Comment by shaloulcy** [comment]
@fuweid Fine. Now We create the volume with the same volume name. If the pouchd has no volume lock, the pouchd will create the volume in the same time, the result is unpredictable.

**Comment by fuweid** [comment]
LGTM

**Comment by fuweid** [comment]
LGTM

**Pull request merged**
