### PR TITLE
feature: add network remove implementation on cli and client side

### LINKED ISSUE #218: [enhancement request] network management implementation
**Issue Description**

we need to polish network management in pouch, in API side, daemon side, client side, doc side and test side. Please record in this issue if some parts are finished.

# network create
- [ ]  network create
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/311
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/311
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/311
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/311
   - [ ]  test:

# network connect
- [ ]  network connect
   - [ ]  API design in swagger:
   - [ ]  daemon side implement:
   - [ ]  client side implement:
   - [ ]  cli implement:
   - [ ]  test:

# network disconnect
- [ ]  network disconnect
   - [ ]  API design in swagger:
   - [ ]  daemon side implement:
   - [ ]  client side implement:
   - [ ]  cli implement:
   - [ ]  test:

# network inspect
- [ ]  network inspect
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/489
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/489
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/571
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/571
   - [ ]  test:

# network ls
- [ ]  network ls
   - [x]  API design in swagger:
   - [x]  daemon side implement:
   - [x]  client side implement:
   - [x]  cli implement:
   - [ ]  test:

# network rm
- [ ]  network rm：https://github.com/alibaba/pouch/pull/489
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/489
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/489
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/560
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/560
   - [x]  test:

### PR DESCRIPTION
**Pull request by ZouRui89**
Signed-off-by: Zou Rui <21751189@zju.edu.cn>

**1.Describe what this PR did**
add network remove implementation on cli and client side
**2.Does this pull request fix one issue?** 
fixes part of #218 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by Letty5411** [comment]
Could you also add a integration test in : test/cli_network_delete_test.go

**Comment by allencloud** [comment]
> Could you also add a integration test in : test/cli_network_delete_test.go

Maybe in a follow-up?  @Letty5411

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
Thanks for your work. I think this is what we need exactly. 🌹 🍻

**Pull request merged**
