### PR TITLE
test : Add test demo for pouch CMD

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty.ll <letty.ll@alibaba-inc.com>

**1.Describe what this PR did**
Add demo test for CMD test. As the skeleton is similar, no need to pay much attention to the common test functions.
**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by Letty5411** [comment]
@allencloud All tests passed on my machine, I will debug in the CI env later.

**Comment by allencloud** [comment]
feel free to tell us if you need any help. @Letty5411 
and /cc @skoo87

**Comment by Letty5411** [comment]
The pull test failures are due to bug#93

**Comment by allencloud** [comment]
What is wrong with the former CI failure?
Have you found the root cause? If that, please share with us. I think it will make our experience on integration test improve a lot. @Letty5411

**Comment by allencloud** [comment]
LGTM
Thanks greatly for the test adding! 👍 👍

**Comment by allencloud** [comment]
Merging, tell us if anything unexpected happens.

**Pull request merged**
