### PR TITLE
feature: basic network manager and add "pouch network ls"

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**1.Describe what this PR did**

1. This PR implement the basic network manager: a simple wrapper of libnetwork controller.
And initialize two default network "host" and "none".

2. Implement command `network ls` in client side and daemon side.

Of course, this PR is only some fundamental code that can be verified, and we still have a lot of work to do to make the network part of pouch really work. 

**2.Does this pull request fix one issue?** 

#218 

**3.Describe how you did it**

**4.Describe how to verify it**

Type command `pouch network ls`, the output as follows:

`
Network Id                                                         Name   Driver   Scope
c5b4631eebd75e572cf3cdac9d4ee433725ad5a41103ad5ea6200564a0b24ebd   host   host     local
336b19280e219b164ae6d979537262706ba1ac3df5f0d1b3fd12fb4541067059   none   null     local
`

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
This is really large. I would like to invite @rudyfly to take a look at this. We need to review carefully and add sufficient test to guarantee the quality.
@YaoZengzeng

**Comment by YaoZengzeng** [comment]
@allencloud Actually the efficient code is little:), but carefully reviewing is needed, because it's the fundamental of pouch network.
Please ping me if there is any problem, and I'll fix it soon:)

**Comment by allencloud** [comment]
First, I left some comment about vendoring before reviewing:
1. It seems that unexpected chars are in vendor.json of your commit.
image

2. It is not OK to have vendor packages in a vendored package, like :  `"origin": "github.com/docker/libnetwork/vendor/github.com/Microsoft/go-winio",` . It is a known vendoring problem in Golang. But I think @rudyfly @yyb196  could help on this, since they have done before witch a proper vendoring way. 

@YaoZengzeng

**Comment by YaoZengzeng** [comment]
@allencloud fixed, go vendor is always annoying.

The first case is result of `pull --rebase` and it's my neglect.
For second case, at first I use `govendor add +external` to put the libnetwork into the vendor, and it will directly put the packages from the libnetwork's vendor to the pouch's vendor, so there will be problem in second case.

So I try to use `govendor fetch github.com/docker/libnetwork` to fetch the libnetwork and its dependencies from remote repo, and update "golang.org/x/sys" to the latest version, then everything is OK.

**Comment by skoo87** [comment]
please wait @rudyfly to review the codes, he is also designing the network, I think he has some other good ideas. Thanks @YaoZengzeng

**Comment by rudyfly** [comment]
I have completed the network module and implemented the base bridge network with libnetwork, but there are some vendor problem need to fix, most ideas are some.

**Comment by YaoZengzeng** [comment]
@rudyfly I'll close this PR and support and support your work #311 :)

**Pull request closed without merging**
