### PR TITLE
Upgrade: Bump to Go 1.10.4

### PR DESCRIPTION
**Pull request by fuweid**
Signed-off-by: Wei Fu <fuweid89@gmail.com>

### Ⅰ. Describe what this PR did

1. update .travis.yml
2. make sure CI runs the client unit test
3. fix golint error

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

no need

### Ⅳ. Describe how to verify it

wait for CI

### CODE REVIEW

**Comment by Ace-Tang** [comment]
Split un-related changes into other pr ? @fuweid

**Comment by Ace-Tang** [comment]
LGTM

**Comment by fuweid** [comment]
> Split un-related changes into other pr

@Ace-Tang all changed is related. The lint policy of new go version has been changed. So I need to modify the source.

**Comment by zhuangqh** [comment]
LGTM

**Comment by allencloud** [comment]
Record the cri-tools:
```
• Failure [3.657 seconds]
[k8s.io] Streaming
/home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
  runtime should support streaming interfaces
  /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:55
    runtime should support attach [Conformance] [It]
    /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:81
    The stdout of exec should be hello
    Expected
        <string>: hello
        
    to equal
        <string>: hello
        
    /home/travis/gopath/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:222
```

And re-run this.

**Comment by zhuangqh** [comment]
please also upgrade the `GO_VERSION` variable in Vagrantfile to 1.10.4.  @fuweid

**Comment by fuweid** [comment]
@zhuangqh thank you!

**Comment by fuweid** [comment]
It seems there is some wrong in  k8s.io/client/spdy implementations. still investigating..

**Comment by fuweid** [comment]
root cause is here https://github.com/kubernetes-sigs/cri-tools/pull/257

**Comment by zhuangqh** [comment]
LGTM

**Comment by HusterWan** [comment]
LGTM

**Pull request merged**
