### PR TITLE
feature: finish resize interface

### PR DESCRIPTION
**Pull request by HusterWan**
Signed-off-by: Michael Wan <zirenwan@gmail.com>

### Ⅰ. Describe what this PR did
finish resize interface:  resize the size of TTY running in the container
```
root@osboxes:wanziren -> pouch --width 10 --height 10 resize test1
root@osboxes:wanziren ->
```

### CODE REVIEW

**Comment by allencloud** [comment]
I am afraid that resize could be an API located in the daemon side. While we need to think carefully that if it is necessary to take this API into a client side command. 
I think sigma has used this API, while not in the way of client command, right?
@furykerry @HusterWan

**Comment by allencloud** [comment]
In the PR description, you mentioned `pouch --width 10 --height 10 resize test1`.
Is it correct? Should it be `pouch resize --width 10 --height 10 test1` since the flags are for the subcommand resize, right?

**Comment by HusterWan** [comment]
@allencloud Yes, the `--height` and `--width` is the flags of subcommand, but `pouch --width 10 --height 10 resize test1` is also work. :)

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
So I think we have removed the cli command part.

**Pull request merged**
