### PR TITLE
feature: complete functions of cni manager

### LINKED ISSUE #748: pouchd can not start without nsenter
### Ⅰ. Issue Description
```
ERRO[2018-02-24 10:33:17.497805285] failed to create new cni manager: exec: "nsenter": executable file not found in $PATH
```

### Ⅱ. Describe what happened
start pouchd daemon
```
pouchd -D
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):Ubuntu-14.04
- Kernel (e.g. `uname -a`):Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@foxmail.com>

### Ⅱ. Does this pull request fix one issue?

fixes #748

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@allencloud PTAL.

**Comment by allencloud** [comment]
Will nsenter be installed in the installation scripts? @YaoZengzeng 
Is this your plan to fix this issue?

**Comment by YaoZengzeng** [comment]
@allencloud This PR won't install nsenter.

This PR completes the function of cni manager and if the cni manager initialized failed, we will return a NoopCniManager which satisfies every interfaces of cni manager but actually does nothing.

By this method, even if the CNI isn't configured appropriately, pouchd won't be crashed.

**Comment by YaoZengzeng** [comment]
@allencloud This PR won't install nsenter.

This PR completes the function of cni manager and if the cni manager initialized failed, we will return a NoopCniManager which satisfies every interfaces of cni manager but actually does nothing.

By this method, even if the CNI isn't configured appropriately, pouchd won't be crashed.

**Comment by allencloud** [comment]
LGTM, I tested on my local machine without nsenter. And it works fine.

**Pull request merged**
