### PR TITLE
cri: remove v1alpha1 codebase

### LINKED ISSUE #2689: [RFC] move CRI v1alpha1 support to END OF LIFE
## What

CRI v1alpha1 version is deprecated nowadays.  **We are going to remove the CRI v1alpha1 interface support on March 31 2019.**  

Please leave a comment if you are using Kubernetes v1.9 and feel free to tell us what's your requirement.

## Support Metrics

Date: Jan 23 2019

| Kubernetes Version | CRI Version | PouchContainer Version |
| --- | --- | --- |
| 1.9 | v1alpha1 | v1.0+ |
| 1.10+ | v1alpha2 | v1.0+|

### PR DESCRIPTION
**Pull request by fuweid**
Signed-off-by: Wei Fu <fuweid89@gmail.com>

### Ⅰ. Describe what this PR did

time to remove v1alpha1 cri

### Ⅱ. Does this pull request fix one issue?

fix #2689

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

none

### Ⅳ. Describe how to verify it

CI

### CODE REVIEW

**Comment by zhuangqh** [comment]
please also remove cri alphav1 related code here 
@fuweid  https://github.com/alibaba/pouch/blob/master/travis_ci.sh#L63

**Comment by allencloud** [comment]
Could we kick the ball? @fuweid @zhuangqh

**Comment by fuweid** [comment]
@allencloud @zhuangqh 

sorry for the late reply. please take a look. If it is good to go, we can move it on.

**Comment by allencloud** [comment]
I would like to invite @zhuangqh to review and merge if reasonable.

**Pull request merged**
