### PR TITLE
bugfix: make attachContainer api compatible with docker

### PR DESCRIPTION
**Pull request by ZYecho**
Signed-off-by: zhangyue <zy675793960@yeah.net>

### Ⅰ. Describe what this PR did
As the title told.

### Ⅱ. Does this pull request fix one issue?

None.

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
None.

### Ⅳ. Describe how to verify it
```
go test -check.f PouchStartSuite
go test -check.f PouchRunSuite
```

### Ⅴ. Special notes for reviews
None.

### CODE REVIEW

**Comment by ZYecho** [comment]
> hi @ZYecho , the pouch daemon doesn't adapt `attach-container` interface for docker. If you wan to do that, the change should be include the daemon side, not just in client.

Thanks, I have updated.

**Comment by fuweid** [comment]
please check the CI result

**Comment by ZYecho** [comment]
Since the current implementation is a little hack, waiting for @fuweid refactor the ctrd.

**Comment by ZYecho** [comment]
do it later.

**Pull request closed without merging**
