### PR TITLE
feature: return empty if the image doesn't exist in CRI mananger and add "basic operations on container" into CI

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

**1.Describe what this PR did**

For method ImageRemove and ImageStatus, if the image doesn't exist, we should return an empty response instead of an error. Hmmm...., bugfix may be more appropriate for this PR 😄 

With this PR and #617 being merged, it is ok for us to add "basic operations on container" CRI test into CI.

**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@allencloud PTAL.

**Comment by allencloud** [comment]
Please add more details in PR description. @YaoZengzeng

**Comment by YaoZengzeng** [comment]
@allencloud updated.

**Comment by allencloud** [comment]
Thanks. @YaoZengzeng 
LGTM

**Pull request merged**
