### PR TITLE
refactor: remove useless 'p.stop' chan

### PR DESCRIPTION
**Pull request by xieyanke**
### Ⅰ. Describe what this PR did
remove useless 'p.stop' chan

### CODE REVIEW

**Comment by HusterWan** [comment]
> @xieyanke Thanks for your contribution. 🍻
Please sign off in each of your commits.

@xieyanke can your sign off your PR, thanks a lot

**Comment by xieyanke** [comment]
@HusterWan OK

**Comment by HusterWan** [comment]
@xieyanke can you explain why we should delete the `stop Channel` ?

**Comment by HusterWan** [comment]
We use this `channel` to wait the process die when execute `stop`, so that before `stop` operation return, the process must have exited. 

If you think this policy is unreasonable, please give us some advices, thanks a lot! @xieyanke

**Comment by xieyanke** [comment]
Sorry, I got it wrong about the function of the p.stop Channel ^_^

**Pull request closed without merging**
