### PR TITLE
bugfix:  fix open the file "/proc/1/mountinfo" , but does't close it.

### LINKED ISSUE #1488: [bug] open file but does't close in lxcfs.go
in "lxcfs.go " file, open the file "/proc/1/mountinfo" , but does't  close it. 

add this code after opening:
`defer f.Close() `

### PR DESCRIPTION
**Pull request by truth**
### Ⅰ. Describe what this PR did
fix open the file "/proc/1/mountinfo" , but does't close it.

### Ⅱ. Does this pull request fix one issue?

fix #1488

### Ⅲ. Describe how you did it
add defer f.Close()

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your contribution. @truth 
Please click the golden mark which has phrase `CLA assistant check` to agree with the CLA, see:

**Comment by truth** [comment]
@allencloud  i signed cla, but  "license/cla " is still  pending.

**Comment by allencloud** [comment]
>  i signed cla

Could you attach the picture that shows you signed the cla?

**Comment by HusterWan** [comment]
@truth maybe this is a problem of github

BTW, please rebase your code, and squash the commits into on commit, thanks a lot

**Pull request closed without merging**
