### PR TITLE
feature: add context in pouch cli

### PR DESCRIPTION
**Pull request by Ace-Tang**
Signed-off-by: Ace-Tang <aceapril@126.com>

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your work.

CI fails:
```
environment/cleanup.go:12:36: not enough arguments in call to apiClient.ImageList
	have ()
	want (context.Context)
environment/cleanup.go:19:34: not enough arguments in call to apiClient.ImageRemove
	have (string, bool)
	want (context.Context, string, bool)
environment/cleanup.go:28:44: not enough arguments in call to apiClient.ContainerList
	have (bool)
	want (context.Context, bool)
environment/cleanup.go:35:38: not enough arguments in call to apiClient.ContainerRemove
	have (string, bool)
	want (context.Context, string, bool)
make: *** [test] Error 2
```

**Comment by Ace-Tang** [comment]
seems that I need to modify test which depends on client package

**Comment by allencloud** [comment]
Great work in client side. 👍

**Comment by allencloud** [comment]
> seems that I need to modify test which depends on client package

Yes, we need to do this.

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
