### PR TITLE
exec with image id

### LINKED ISSUE #374: [feature required] pouch  create should support create container using Image ID
**Issue Description**

**Describe what happened**:
Create container using image id failed. And the error message should also be changed
```
#pouch images
IMAGE ID       IMAGE NAME                                       SIZE
68effe31a4ae   reg.docker.alibaba-inc.com/base/busybox:latest   686.62 KB

#pouch create 68effe31a4ae top
Error: failed to create container: {"message":"image: 68effe31a4ae:latest: not found"}
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jomenxiao**
**1.Describe what this PR did**
exec support image id
**2.Does this pull request fix one issue?** 
fixes #374 
**3.Describe how you did it**
check image's name/id has existed before request HTTP server
**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your contribution. @jomenxiao 🥂 

> check image's name/id has existed before request HTTP server

I am afraid in your code, you use an ImageList request torwards HTTP server(pouch daemon) to get image list from server then check the existence of user's input image.

So, you still requested the daemon. To be honest, maybe it is not the way it should be.

Feel free to tell us if you need any help.

**Comment by jomenxiao** [comment]
ok, 
when the image not existed,  the pouch daemon tries to pull it.
I miss it.
and what's your idea and suggestion?

**Comment by allencloud** [comment]
My suggestion is that, pouch cli could have ability to pass image id, and it is the pouch daemon side that deals with this image id and try to find the actual image with reference(image:tag).

So, I would suggest that daemon side is a good way. Maybe more input from @0x04C2 😄

**Comment by skoo87** [comment]
Now the daemon side is supported to create container with image's id.

**Comment by allencloud** [comment]
I think we need to add more details of all aspects which support image id in swagger.yml and this will help to sync information among us. @skoo87

**Pull request closed without merging**
