### PR TITLE
bugfix: fix return code when pull image occurred error

### PR DESCRIPTION
**Pull request by HusterWan**
Signed-off-by: HusterWan <zirenwan@gmail.com>

**1.Describe what this PR did**
fix return code when pouch pull image occurred error

**2.Does this pull request fix one issue?** 
fixes https://github.com/alibaba/pouch/issues/237

**3.Describe how you did it**

**4.Describe how to verify it**
```
[root@docker-registry github.com]# pouch pull docker.io/library/centos:ttt
docker.io/library/centos:ttt: resolving      |--------------------------------------|
elapsed: 0.4 s                total:   0.0 B (0.0 B/s)
Error: failed to pull image: docker.io/library/centos:ttt not found
[root@docker-registry github.com]# echo $?
1
```

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks for your work. I suggest you could add this email zirenwan@gmail.com in your github settings. Then github will detect you are not the-first-time-contributor and you can be list in the contributor list of pouch, since github uses emails to check this.

In addition, in the PR description, if this PR fixes some issue, you should `fixes #num`, then if the pr is merged, github will automatically close issue num. If you just add #num , no auto-close will happen.

@HusterWan

**Comment by skoo87** [comment]
LGTM

**Comment by HusterWan** [comment]
@allencloud thanks for your guide, i have reconfigured my github setting

**Comment by allencloud** [comment]
LGTM
Thanks a lot. @HusterWan

**Pull request merged**
