### PR TITLE
bugfix: del endpoint after failing to create endpoint

### PR DESCRIPTION
**Pull request by faycheng**
Signed-off-by: 程飞 <fay.cheng.cn@gmail.com>

### Ⅰ. Describe what this PR did

del endpoint after failing to create endpoint

### CODE REVIEW

**Comment by allencloud** [comment]
Is it a bugfix for issue https://github.com/alibaba/pouch/issues/1068? 
If that, please add that in the pr description. Thanks a lot. @faycheng

**Comment by faycheng** [comment]
hi, @allencloud , i am afraid that this PR could not fix #1068 . And thanks for your comment.

**Comment by allencloud** [comment]
I am wondering if we could add an integration test to cover this. @faycheng

**Comment by allencloud** [comment]
That is all right. To be honest, this is indeed some kind of complex. @faycheng

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
