### PR TITLE
support annotation in container update api

### PR DESCRIPTION
**Pull request by wangforthinker**
Signed-off-by: allen.wang <allen.wq@alipay.com>

### Ⅰ. Describe what this PR did
Support to update annotations in Container Update API.

### Ⅱ. Does this pull request fix one issue?

fix https://github.com/alibaba/pouch/issues/2724.

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
add test TestUpdateAnnotation.

### Ⅳ. Describe how to verify it
by CI test.

### CODE REVIEW

**Comment by wangforthinker** [comment]
ping @rudyfly

**Comment by wangforthinker** [comment]
ping @Ace-Tang

**Comment by rudyfly** [comment]
CI failed.

**Comment by wangforthinker** [comment]
ping @rudyfly

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
