### PR TITLE
refactor: abstract common api client

### PR DESCRIPTION
**Pull request by Ace-Tang**
Signed-off-by: Ace-Tang <aceapril@126.com>

### CODE REVIEW

**Comment by allencloud** [comment]
CI fails
```
# github.com/alibaba/pouch/test/request
request/request.go:118:2: cannot use client.CommonAPIClient as type *client.APIClient in return argument: need type assertion
make: *** [test] Error 2
```

And could you tell us more about the reason why you did this? @Ace-Tang

**Comment by Ace-Tang** [comment]
I did this pr for two reason.
1.  In package client , someone has abstracted container and image api client as `ContainerAPIClient` and `ImageAPIClient`
2. I thought that abstract these api client as a common interface is a good idead, so I did this.

WDYT, @allencloud ,  the pr is not necessary.

**Comment by allencloud** [comment]
To be honest, I would definitely say that this PR is very important for the project. Although it brings less effect compared to the original one, consistency and reader-friendly is very important for an open source project. I must 👍 for your idea. @Ace-Tang

**Comment by allencloud** [comment]
LGTM, thanks a lot for the work. @Ace-Tang

**Pull request merged**
