### PR TITLE
typo: fix misspells in code and comments

### PR DESCRIPTION
**Pull request by idealhack**
### Ⅰ. Describe what this PR did

fix misspells in code and comments

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your work. Actually this is a vendor package and we have no plan to main the code of this part. I am afraid we cannot merge this. @idealhack

**Comment by allencloud** [comment]
> I see, but why there are different folders for vendor packages?

This is a good question. Lots of things have been discussed before, like: 
https://github.com/alibaba/pouch/issues/1344
https://github.com/alibaba/pouch/issues/428
https://github.com/alibaba/pouch/issues/750

I think we do need to take into vendor the latest version into consideration. WDYT? @rudyfly

**Comment by fuweid** [comment]
@allencloud This is not flaky case. The pouchd cannot remove the running task. We are still investigating the issue.

**Comment by idealhack** [comment]
I'll keep this open for now. Feel free to close it when you open new ones for the ci and dependency issues.

**Comment by allencloud** [comment]
Could you help to vendor the latest libnetwork package with govendor tool? @idealhack 
I think this is what we wish to finish. We encourage you to finish it very much and feel free to tell us if you have any problem when doing this.

**Comment by idealhack** [comment]
@allencloud OK, I'll give it a try.

**Comment by idealhack** [comment]
Since #1344 is open, let's resolve the dependency issue in that thread.

Feel free to close this one when you open new ones for the ci issue.

**Comment by allencloud** [comment]
Thanks @idealhack 
While I do not think this issue could help. And I am closing it.

**Pull request closed without merging**
