### PR TITLE
doc: fix word misspell

### PR DESCRIPTION
**Pull request by raoqi**
Signed-off-by: raoqi <1020216950@qq.com>

### CODE REVIEW

**Comment by fuweid** [comment]
Hi @raoqi, welcome! 

Thank you for your work. LGTM. If the CI passes, I will merge this PR.

Welcome to contribute the pouch!

**Comment by fuweid** [comment]
Hold on a sec, @raoqi , the Author is `unknown`? If it's mistake, please let me know. :)

**Comment by allencloud** [comment]
> the Author is unknown

I think it is OK.  We do not strict to much on commit sign off.

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
