### PR TITLE
should use time.Since instead of time.Now().Sub

### PR DESCRIPTION
**Pull request by wgliang**
### Ⅰ. Describe what this PR did
should use time.Since instead of time.Now().Sub

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Describe how you did it

use time.Since instead of time.Now().Sub

### Ⅳ. Describe how to verify it
All Test.

### Ⅴ. Special notes for reviews

NONE

### CODE REVIEW

**Comment by HusterWan** [comment]
@wgliang thanks a lot for your work 😄 

extra/libnetwork is a package from outside,  so we should not change the code

**Comment by wgliang** [comment]
Ok @allencloud I'm sorry for my fault.

**Comment by HusterWan** [comment]
@wgliang it's ok, please enjoy hacking !!!

**Comment by allencloud** [comment]
Thanks a lot for your contribution. While I am afraid this is not in the scope of Pouch like @HusterWan mentioned. I am closing this.

**Pull request closed without merging**
