### PR TITLE
feature: support Installing pouch on various distributions

### LINKED ISSUE #67: [feature request] support Installing pouch on various distributions
**Issue Description**
support Installing pouch on various distributions

**Describe what happened**:
NONE

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
NONE

**Anything else we need to know?**:
NONE

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zzchun**
Signed-off-by: Zhanchun Zhang zzchun@zju.edu.cn

**1.Describe what this PR did**
build rpm and deb packages for pouch 

**2.Does this pull request fix one issue?** 
fixes #67

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by Letty5411** [comment]
The CRI tests failed because CRI_FOCUS="" and CRI_SKIP="", all tests are run. We may need to fix this in branch 0.1.0. WDYT @allencloud

**Comment by allencloud** [comment]
Do we need to push these files to the master branch? @zzchun

**Comment by allencloud** [comment]
> The CRI tests failed because CRI_FOCUS="" and CRI_SKIP="", all tests are run. We may need to fix this in branch 0.1.0.

I am afraid my answer is no. Actually we could fix them in master, and make sure the 0.2.x will never have the same issue. This work does not need us to do backporting. @zzchun @Letty5411 

So maybe pushing to master is what we need urgently. If we can reach consensus, let us kick the ball ASAP.

**Comment by zzchun** [comment]
@allencloud these files have been merged to the master branch , I am trying push to 0.1.x now

**Comment by allencloud** [comment]
I think we have not ubuntu distribution's installing Pouch yet. Could you first complete https://github.com/alibaba/pouch/blob/master/INSTALLATION.md#ubuntu first. I think this is really important for our users. @zzchun

**Comment by allencloud** [comment]
I think this could be closed, right. Since we will never update 0.1.x branch. And we will remove this branch soon. Right?
If you confirmed this, please close this PR. Thanks. @zzchun

**Pull request closed without merging**
