### PR TITLE
bugfix: fix pouch pull panic : unexpected format character

### PR DESCRIPTION
**Pull request by HusterWan**
Signed-off-by: HusterWan <zirenwan@gmail.com>

**1.Describe what this PR did**
pull pull image panic:
```
[root@docker-registry github.com]# pouch pull registry.hub.docker.com/library/busybox:latest
registry.hub.docker.com/library/busybox:latest:                                   resolved       %!f(PANIC=1: unexpected format character)
index-sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0:    done           %!f(PANIC=1: unexpected format character)
manifest-sha256:91ef6c1c52b166be02645b8efee30d1ee65362024f7da41c404681561734c465: done           %!f(PANIC=1: unexpected format character)
layer-sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5:    done           %!f(PANIC=1: unexpected format character)
config-sha256:6ad733544a6317992a6fac4eb19fe1df577d4dec7529efec28a5bd0edad0fd30:   done           %!f(PANIC=1: unexpected format character)
elapsed: 1.4 s                                                                    total:   0.0 B (0.0 B/s)
```

**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
Oh, it is my fault that I merged a previous commit. Thanks a lot for your help. @HusterWan

**Comment by HusterWan** [comment]
@allencloud ci failed, maybe this is the problem:
```
INFO[2017-12-26 12:54:42.716173587] fetch progress exited, ref: registry.hub.docker.com/library/busybox:latest:latest. 
ERRO[2017-12-26 12:54:42.716296157] failed to pull image registry.hub.docker.com/library/busybox:latest:latest: failed to pull image: registry.hub.docker.com/library/busybox:latest:latest not found 
INFO[2017-12-26 12:54:42.717215974] Calling DELETE /images/TestDeleteNonExisting, client @ 
INFO[2017-12-26 12:54:42.725856416] Calling POST /volumes/create, client @       
INFO[2017-12-26 12:54:42.729156271] Calling DELETE /volumes/TestVolumeCreateOk, client @ 
INFO[2017-12-26 12:54:42.733713040] Calling DELETE /volumes/TestDeleteNonExisting, client
```

**Comment by allencloud** [comment]
`registry.hub.docker.com/library/busybox:latest:latest` two `latest` in the name?

**Comment by HusterWan** [comment]
This log is printed by pouchd of ci

**Comment by 0x04C2** [comment]
Hi @HusterWan , @allencloud , the reason is here. https://github.com/alibaba/pouch/pull/412#issuecomment-353977743

**Comment by 0x04C2** [comment]
Link to #412

**Comment by allencloud** [comment]
Please rebase to the latest master, since PR https://github.com/alibaba/pouch/pull/436 which solved flaky test has been merged. Thanks.

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
