### PR TITLE
test: unit test for request cache of stream server

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### Ⅱ. Does this pull request fix one issue?

fixes part of #1756

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@fuweid PTAL.

**Comment by allencloud** [comment]
In this pull request, I read the unit test code in the change, while I think these are quite good.
However, I still have some confusion to share with others:

> When adding unit test, which one is better? Unit test for single function, or unit test for com比national logic for procedure?

If we have a function Insert, then we add a unit test `TestInsert`. This is for function.

If we we have function insert, unique and others, we add a unit test `TestRequestCacheBasic` which is a combinational logic. Or the latter one is some kind of integration test for couple of functions.

What should we do, or do we need to rule to classify this?

Maybe,  `for function` is a must-do, `combinational logic` is an option?

Wish to get more input? @YaoZengzeng @fuweid @Letty5411 @chuanchang @HusterWan @zhuangqh

**Comment by Starnop** [comment]
LGTM.

**Comment by allencloud** [comment]
Thanks for your review. @Starnop

**Pull request merged**
