### PR TITLE
fix: keep meta data complete

### PR DESCRIPTION
**Pull request by Ace-Tang**
before updating meta.json on disk, write a new file for the new content, in case
that if it fails to write new file(like no space on disk), we can still
have a completed file. Avoid meta.json broken, in this way, we may
hardly recover meta data
Signed-off-by: Ace-Tang <aceapril@126.com>

## The design 

1. use timestamp as a suffix of a backfile, consider that if one time back up file is not deleted, backup file will be covered, generally it will be ok, but sometimes it may error.
2. do not use backup file to do recovery automatically, first this case is really unusual, if it happens, we should check and do recovery by manual. If automatic recovery fails, we may never get origin file. So I do not suggest automatic recovery.

Design has changed according to the review, please check.

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

no.

### CODE REVIEW

**Comment by allencloud** [comment]
Is there any possibility that before backuping the original `meta.json`, the disk have already been full, and then the backup fails？ @Ace-Tang

**Comment by Ace-Tang** [comment]
> Is there any possibility that before backuping the original meta.json, the disk have already been full, and then the backup fails？ @Ace-Tang

it will return error, then, meta data update also fails.
```
if _, err := os.Stat(name); err == nil {
+               if err := os.Rename(name, backupFile); err != nil {
+                       return fmt.Errorf("failed to backup file %s: %s", name, err)
+               }
+       }
+
```
And if the container is first time to be created, the created process will fail, since disk is full.

**Comment by Ace-Tang** [comment]
@allencloud , modify as you suggest offline, PTAL.

**Comment by xiaoxubeii** [comment]
I think you should adjust the content of pr according to your recently changes. These changes don't backup the original configuration but create a new target file and replace the origin.

**Comment by Ace-Tang** [comment]
@xiaoxubeii ， I have alreay update content of pr, but just not update the auto-generated one, now I update it.

**Comment by allencloud** [comment]
LGTM, while I would invite @fuweid to take another review.

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
