### PR TITLE
bugfix: repair the script of creating k8s cluster with pouch in Ubuntu 16.04.5

### PR DESCRIPTION
**Pull request by fengzixu**
Signed-off-by:  fengzixu <hnustphoenix@gmail.com>

### Ⅰ. Describe what this PR did

1. revise the binary path of pouchd
2. delete the `systemctl enable pouch`

### Ⅱ. Does this pull request fix one issue?

https://github.com/alibaba/pouch/issues/2610

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

Just the script.

### Ⅳ. Describe how to verify it

I found the clearing the VM and installed the Ubuntu. The info of the operating system as below:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
root@xr-service-mesh-lab
```
Then I run scripts called `allinone_aliyun.sh` and `allinone.sh`. It can created the Kubernetes cluster which pouch container engine for me.

```
root@xr-service-mesh-lab:/home/root/workspace/go-project/src/github.com/alibaba/pouch/hack/kubernetes# kubectl get pods
NAME                    READY     STATUS    RESTARTS   AGE
nginx-db897d5d4-l6h2v   1/1       Running   0          19m
nginx-db897d5d4-wdkmz   1/1       Running   0          19m
root@xr-service-mesh-lab:/home/root/workspace/go-project/src/github.com/alibaba/pouch/hack/kubernetes#
```

### Ⅴ. Special notes for reviews

I just revise the script which was processed in Ubuntu.

### CODE REVIEW

**Comment by fengzixu** [comment]
@fuweid Please review it.

**Comment by fengzixu** [comment]
Thanks for everyone. This is my final commit in 2018 for pouch. Happy New Year! See you 2019.

**Comment by fengzixu** [comment]
Thanks for everyone. This is my final commit in 2018 for pouch. Happy New Year! See you 2019.

**Comment by allencloud** [comment]
> See you 2019.

So good to have you in 2018. Wish you a happy new year. And wish we could have more technical communication in 2019. @fengzixu

**Comment by fuweid** [comment]
@fengzixu  Thanks!
see you in 2019

**Pull request merged**
