### PR TITLE
test: remove help api test and add info api test 

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty.ll <letty.ll@alibaba-inc.com>

**1.Describe what this PR did**
Delete old help demo api test, as there isn't a /help api. 
Add an info demo api test.
**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by zhubingbing** [comment]
how to use “test-api” to test ？can u provide  simple doc ？

**Comment by allencloud** [comment]
Yes, I think we need to add a target name `integration-test` in Makefile for users to easily test that. @Letty5411 @sunyuan3 
Could you help that in contribution?

**Comment by Letty5411** [comment]
@zhubingbing this could be added later.

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
