### PR TITLE
[WIP] docs: kubernetes compatibility board

### LINKED ISSUE #2590: [feature request] support more kubernetes version e2e test
## Why you need it?

Currently the latest upstream kubernetes release has been developed to be 1.13, while the default test version of kubernetes in PouchContainer is just 1.10, see https://github.com/alibaba/pouch/blob/master/hack/testing/run_daemon_cri_e2e.sh#L64

```
# integration::run_daemon_cri_test_e2e_cases runs CRI e2e test cases.
integration::run_daemon_cri_test_e2e_cases() {
  local cri_runtime code KUBERNETES_VERSION
  cri_runtime=$1

  if [[ "${cri_runtime}" == "v1alpha1" ]]; then
    KUBERNETES_VERSION="release-1.9"
  else
    KUBERNETES_VERSION="release-1.10"
  fi
```

Thus we have not tested kubernetes 1.11, 1.12 or 1.13.

In fact, we will try to choose several reasonable versions in node end-to-end test in CI system.

## How it could be?

In travisCI system, we support more new released version kubernetes testing.

## Other related information

none

### PR DESCRIPTION
**Pull request by zhuangqh**
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>

### Ⅰ. Describe what this PR did

Create a board to illustrate the compatibility against kubernetes.

### Ⅱ. Does this pull request fix one issue?

fixes #2590 

### Ⅴ. Special notes for reviews

Running the compatibility test with the aid of travis CI.

### CODE REVIEW

**Comment by Starnop** [comment]
```
Detected go version: go version go1.10.4 linux/amd64.
Kubernetes requires go1.11.1 or greater.
Please install go1.11.1 or later.]
```

It seems that we are not ready for `Kubernetes 1.13`. Maybe we can test it locally. 😄

**Comment by zhuangqh** [comment]
> ```
> Detected go version: go version go1.10.4 linux/amd64.
> Kubernetes requires go1.11.1 or greater.
> Please install go1.11.1 or later.]
> ```
> It seems that we are not ready for `Kubernetes 1.13`. Maybe we can test it locally. 😄

Thanks for pointing out. I will test it after we upgrade to go1.11

**Comment by zhuangqh** [comment]
- [ ]  upgrade to go 1.11+

**Comment by zhuangqh** [comment]
if we support the kubernetes 1.14, I will reopen

**Pull request closed without merging**
