### PR TITLE
test: simpler test in cli_run_with_privileged_test.go

### PR DESCRIPTION
**Pull request by Ace-Tang**
remove check exitcode, check output error is enough

Signed-off-by: Ace-Tang <aceapril@126.com>

### Ⅰ. Describe what this PR did

remove check exitcode, check output error is enough in cli_run_with_privileged_test.go

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

has test

### CODE REVIEW

**Comment by Ace-Tang** [comment]
@fuweid , as you advised, I has fix the test

**Comment by allencloud** [comment]
Could you help to take a look of this? @ZYecho 🐳 🦁

**Comment by ZYecho** [comment]
make sense, LGTM

**Comment by HusterWan** [comment]
LGTM

**Pull request merged**
