### PR TITLE
[test] Print error log in CI.

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

### Ⅰ. Describe what this PR did
Print error log in CI. Don't redirect the error log to a file.

### Ⅱ. Does this pull request fix one issue?
Yes. CI did miss some error logs. We need to print these logs.

### Ⅲ. Describe how you did it
Print error log in CI.

### Ⅳ. Describe how to verify it
NA

### Ⅴ. Special notes for reviews
NA

### CODE REVIEW

**Comment by sunyuan3** [comment]
This PR isn't the root cause of the CI failure.

**Comment by Letty5411** [comment]
LGTM

**Comment by Letty5411** [comment]
@sunyuan3 please change the commit message to :  test:xxx

**Comment by sunyuan3** [comment]
@Letty5411 Done.

**Pull request merged**
