### PR TITLE
test: add cases for testing imageCache.get

### PR DESCRIPTION
**Pull request by faycheng**
Signed-off-by: 程飞 <fay.cheng.cn@gmail.com>

### Ⅰ. Describe what this PR did

add cases for testing `imageCache.get`

### Ⅲ. Describe how you did it

this pr is related to issue #975 & pr #973 .please don't merge it before merging #973 

### Ⅳ. Describe how to verify it

make unit-test

### CODE REVIEW

**Comment by HusterWan** [comment]
@faycheng if working your pr in process,  you can add prefix [WIP] in your pr title.  Thanks a lot.

**Comment by faycheng** [comment]
@HusterWan Done.

**Comment by YaoZengzeng** [comment]
@faycheng please rebase your PR, thanks :)

**Comment by faycheng** [comment]
@YaoZengzeng Done.
And in order to trigger travis ci again, i will mark this pr closed and then mark it opened.

Travis log:
```
> sudo apt-get update -qq
W: The repository 'http://www.apache.org/dist/cassandra/debian 39x Release' does not have a Release file.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-amd64/Packages  502  Bad Gateway [IP: 52.27.175.225 80]
E: Failed to fetch http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-i386/Packages  502  Bad Gateway [IP: 52.27.175.225 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -qq" failed and exited with 100 during .
```

**Comment by faycheng** [comment]
Remove the WIP label

**Comment by YaoZengzeng** [comment]
LGTM

**Pull request merged**
