### PR TITLE
bugfix: change Flags to PersistentFlags

### PR DESCRIPTION
**Pull request by faycheng**
### Ⅰ. Describe what this PR did

change Flags to PersistentFlags

### Ⅴ. Special notes for reviews

Daemon config file is invalid while using Flags.

```
> cat /etc/pouch/config.json
{"debug": true}
> pouchd
ERRO[0000] failed to load daemon file: unknow flags: debug
```

### CODE REVIEW

**Comment by allencloud** [comment]
Could you help to take a look at this? @HusterWan 
Also cc @yyb196 Maybe it is related to the issue we discussed several days ago.

**Comment by HusterWan** [comment]
> > cat /etc/pouch/config.json
{"debug": true}
> pouchd
ERRO[0000] failed to load daemon file: unknow flags: debug

@faycheng i cannot replay this error, i think this problem maybe caused by PR #917 , we have revert this code. 

so maybe you should rebase you local code with upstream/master, and try again. 

if you can still occur this error, please let me know, thanks a lot.

**Comment by faycheng** [comment]
@HusterWan you are right.soon after this error raised, i wished only to fix it and i didn't find it reverted.i feel deeply ashamed for creating this pr. sorry

**Comment by allencloud** [comment]
That is all right. Never mind. We sincerely appreciate your work. Feel free to tell us if you meet any question here.

**Pull request closed without merging**
