### PR TITLE
test: add RunCmd lib function to reduce the work of developing cli tests

### PR DESCRIPTION
**Pull request by Letty5411**
Signed-off-by: letty.ll <letty.ll@alibaba-inc.com>

**1.Describe what this PR did**
Add a lib function: RunCmd. And a demo of usage in : pouch_cli_version_test.go.

With this function, user could fill a struct with their CMD and expected results, this function will execute CMD, check results and assert failure if there is error.

The usage is as following:
```
+	cmd = PouchCmd{
 +		args:        "version",
 +		result:      true,
 +		outContains: "APIVersion",
 +	}
 +	RunCmd(c, &cmd)
```
A failure log is as following:
```
#go test -check.f PouchVersionSuite

▽
package main

----------------------------------------------------------------------
FAIL: pouch_cli_version_test.go:21: PouchVersionSuite.TestPouchVersion

pouch_cli_version_test.go:31:
    RunCmd(c, &cmd)
lib_common.go:110:
    // Add "(?s)" to match "\n", add ".*" to return success as lone as ret.Stdout() contains cmd.stdout
    c.Assert(ret.Stdout(), check.Matches, "(?s).*"+cmd.stdout+".*",
        check.Commentf("[FAIL]: CMD[%s %s] return %d,\n"+
            "Stdout: %s\n Stderr: %s",
            cmd.binary, cmd.args, ret.ExitCode, ret.Stdout(), ret.Stderr()))
... value string = "" +
...     "Arch:            amd64\n" +
...     "BuildTime:       2017-12-01T17:24:10.494219447+08:00\n" +
...     "GitCommit:       \n" +
...     "GoVersion:       go1.8.3\n" +
...     "KernelVersion:   \n" +
...     "Os:              linux\n" +
...     "Version:         0.1.0-dev\n" +
...     "APIVersion:      1.24\n"
... regex string = "(?s).*xxxxAPIVersion.*"
... 
[FAIL]: CMD[/usr/local/bin/pouch version] return 0,
Stdout: 
Arch:            amd64
BuildTime:       2017-12-01T17:24:10.494219447+08:00
GitCommit:
GoVersion:       go1.8.3
KernelVersion:
Os:              linux
Version:         0.1.0-dev
APIVersion:      1.24

 Stderr:

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.10s)
FAIL
exit status 1
FAIL	github.com/alibaba/pouch/test	0.197s
```

**2.Does this pull request fix one issue?** 

**3.Describe how you did it**

**4.Describe how to verify it**

**5.Special notes for reviews**

### CODE REVIEW

**Comment by allencloud** [comment]
`GoVersion:       go1.8.3` still exists in repo. It is strange 🤔 
I think we have updated that in master?

**Comment by Letty5411** [comment]
@allencloud I build pouch on my own test machine, maybe it is related to my ENV?

**Comment by allencloud** [comment]
Ok, Please upgrade your golang version when you have time. 😄

**Comment by allencloud** [comment]
LGTM

**Comment by Letty5411** [comment]
@allencloud Thanks a lot~

**Pull request merged**
