### PR TITLE
bugfix: specify both cmd and its args when create a container

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### Ⅰ. Describe what this PR did

Actually I forget to specify the args of the cmd executed in the container, so fill it in this PR.

### CODE REVIEW

**Comment by allencloud** [comment]
Please provide more details about this pull request in pull request description. @YaoZengzeng 
Thanks a lot.

**Comment by YaoZengzeng** [comment]
@allencloud PTAL

**Comment by YaoZengzeng** [comment]
With this PR, the node-e2e test result will be:

Ran 186 of 258 Specs in 1501.814 seconds
FAIL! -- 146 Passed | 40 Failed | 0 Pending | 72 Skipped 

exciting 😄

**Comment by rudyfly** [comment]
LGTM

**Pull request merged**
