### PR TITLE
support filter format map[string]map[string]bool and change multi label filter to And match

### PR DESCRIPTION
**Pull request by wangforthinker**
### Ⅰ. Describe what this PR did
Support filter format map[string]map[string]bool and change multi label filter to And match.

### Ⅱ. Does this pull request fix one issue?

none.

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
add test.

### Ⅳ. Describe how to verify it
by test.

### CODE REVIEW

**Comment by ZYecho** [comment]
could you explain why we need to change multi label filter to And match?  the behavior in docker I think is OR match when use multi filter, should we be consistent with docker? @wangforthinker

**Comment by allencloud** [comment]
Any update on this? @wangforthinker 
Could you give some feedback on @ZYecho 's question?

**Comment by wangforthinker** [comment]
> could you explain why we need to change multi label filter to And match? the behavior in docker I think is OR match when use multi filter, should we be consistent with docker? @wangforthinker

**Comment by wangforthinker** [comment]
> could you explain why we need to change multi label filter to And match? the behavior in docker I think is OR match when use multi filter, should we be consistent with docker? @wangforthinker

Thanks for your question. As I know, label multi filter in docker is AND match. And the behavior is more suitable for daily usage habits. @ZYecho

**Comment by ZYecho** [comment]
> > could you explain why we need to change multi label filter to And match? the behavior in docker I think is OR match when use multi filter, should we be consistent with docker? @wangforthinker
> 
> Thanks for your question. As I know, label multi filter in docker is AND match. And the behavior is more suitable for daily usage habits. @ZYecho

Yep I think you're right.  the multi label filter was OR match, but multi reference/name filter was AND match.

**Comment by wangforthinker** [comment]
@HusterWan @allencloud Could you review this PR?

**Comment by cxz66666** [comment]
Thanks for your contribution!  At now there is no progress about this [issue](https://github.com/moby/moby/issues/39172#issue-440407387), so I think we can be consistent with docker. But can you explain about why we need support `map[string]map[string]bool` format? After getting your response, I will review and merge this pr ASAP!

**Review by cxz66666 — APPROVED** [review]
LGTM.

**Pull request merged**
